// ---------------------------------------------------------------------------
// Focus Kitchen — data-driven pixel kitchen timer
// All sprite geometry below is loaded from data/*.json, which was generated by
// measuring the source reference sheets (see data/*.json "source_bbox" / "note"
// fields for provenance). Nothing here hardcodes sprite pixel coordinates.
// ---------------------------------------------------------------------------

const STORAGE_KEY = 'focus-kitchen-unlocked-recipes';
const SESSION_KEY = 'focus-kitchen-session';

const state = {
  data: { ingredients: null, tiles: null, chef: null, recipes: null },
  unlocked: loadUnlocked(),
  timer: { totalMs: 0, endAt: 0, tickHandle: null, introTimers: [], introDone: false, paused: false, remainingAtPauseMs: 0 },
  animators: [],
};

function loadUnlocked() {
  try {
    return new Set(JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'));
  } catch { return new Set(); }
}
function saveUnlocked() {
  localStorage.setItem(STORAGE_KEY, JSON.stringify([...state.unlocked]));
}

function saveSession() {
  const t = state.timer;
  if (!t.totalMs) { localStorage.removeItem(SESSION_KEY); return; }
  localStorage.setItem(SESSION_KEY, JSON.stringify({
    totalMs: t.totalMs,
    endAt: t.paused ? null : t.endAt,
    paused: t.paused,
    remainingAtPauseMs: t.remainingAtPauseMs,
  }));
}
function clearSession() {
  localStorage.removeItem(SESSION_KEY);
}
function loadSession() {
  try { return JSON.parse(localStorage.getItem(SESSION_KEY)); } catch { return null; }
}

// ---------------------------------------------------------------------------
// Data loading
// ---------------------------------------------------------------------------

async function loadData() {
  const [ingredients, tiles, chef, recipes] = await Promise.all([
    fetch('data/ingredients.json').then(r => r.json()),
    fetch('data/tiles.json').then(r => r.json()),
    fetch('data/chef_animations.json').then(r => r.json()),
    fetch('data/recipes.json').then(r => r.json()),
  ]);
  state.data = { ingredients, tiles, chef, recipes };
}

function tileById(id) {
  return state.data.tiles.sprites.find(s => s.id === id);
}

// ---------------------------------------------------------------------------
// Animator: cycles an <img> through a named animation section's frames
// ---------------------------------------------------------------------------

class Animator {
  constructor(imgEl, sections) {
    this.img = imgEl;
    this.sections = sections;
    this.handle = null;
    this.frameIndex = 0;
    this.current = null;
    this.onComplete = null;
  }
  play(name, { onComplete } = {}) {
    this.stop();
    const section = this.sections[name];
    if (!section) return;
    const isSwitch = this.current !== null && this.current !== name;
    this.current = name;
    this.frameIndex = 0;
    this.onComplete = onComplete || null;

    const start = () => {
      this._render(section);
      this.img.style.opacity = '1';
      this.handle = setInterval(() => this._advance(section), section.frame_ms);
    };
    if (isSwitch) {
      this.img.style.opacity = '0';
      setTimeout(start, 180);
    } else {
      start();
    }
  }
  _advance(section) {
    this.frameIndex++;
    if (this.frameIndex >= section.frames.length) {
      if (section.loop) {
        this.frameIndex = 0;
      } else {
        this.frameIndex = section.frames.length - 1;
        this._render(section);
        this.stop();
        if (this.onComplete) this.onComplete();
        return;
      }
    }
    this._render(section);
  }
  _render(section) {
    this.img.src = section.frames[this.frameIndex].file;
  }
  stop() {
    if (this.handle) { clearInterval(this.handle); this.handle = null; }
  }
}

// ---------------------------------------------------------------------------
// Scene composition — layers floor / wall / counters / appliances / chef
//
// The scene is built in three clean horizontal bands so nothing overlaps:
//   wall band (0–38%)     : upper cabinets, hood, fridge top
//   counter band (38–64%) : counter run, stove, fridge body
//   floor band (64–100%)  : open tile floor where the chef stands
// ---------------------------------------------------------------------------

function composeKitchenScene(container, mode) {
  container.innerHTML = '';
  const t = id => tileById(id).file;

  container.style.backgroundImage = `url(${t('floor_tile_stone')})`;
  container.style.backgroundSize = '96px 96px';
  container.style.backgroundRepeat = 'repeat';
  container.style.backgroundPosition = 'top';

  const floor = document.createElement('div');
  floor.className = 'scene-layer';
  Object.assign(floor.style, {
    left: 0, right: 0, bottom: 0, height: '38%', zIndex: '0',
    backgroundImage: `url(${t('floor_tile_tan')})`,
    backgroundSize: '96px 106px', backgroundRepeat: 'repeat',
  });
  container.appendChild(floor);

  const layers = [
    { id: 'cabinet_upper_run', style: { left: '4%', top: '3%', width: '52%', zIndex: 2 } },
    { id: 'extractor_hood',    style: { left: '20%', top: '16%', width: '17%', zIndex: 3 } },
    { id: 'fridge',            style: { right: '5%', top: '4%', width: '15%', zIndex: 2 } },
    { id: 'cabinet_lower_run', style: { left: '4%', top: '37%', width: '62%', zIndex: 2 } },
    { id: 'stove_range',       style: { left: '9%', top: '35%', width: '34%', zIndex: 3 } },
  ];
  for (const layer of layers) {
    const img = document.createElement('img');
    img.className = 'scene-layer';
    img.src = t(layer.id);
    Object.assign(img.style, { position: 'absolute', height: 'auto', ...layer.style, zIndex: String(layer.style.zIndex) });
    container.appendChild(img);
  }

  const chefAnchor = mode === 'cooking'
    ? { left: '15%', top: '46%', width: '92px', zIndex: 4 }   // standing at the stove
    : { left: '30%', top: '72%', width: '96px', zIndex: 4 };  // idle, open floor

  return { chefAnchor };
}

function placeChef(container, anchor, imgId) {
  const img = document.createElement('img');
  img.id = imgId;
  img.className = 'chef-sprite scene-layer';
  Object.assign(img.style, { position: 'absolute', height: 'auto', ...anchor });
  container.appendChild(img);
  return img;
}

// A calm, single strip of distinct ingredient icons — no repeats, no
// left/right walls of icons that made the home screen feel cluttered.
function decorateBorders() {
  const sprites = state.data.ingredients.sprites;
  const count = 9;
  const stride = Math.floor(sprites.length / count);
  const chosen = [];
  for (let i = 0; i < count; i++) chosen.push(sprites[i * stride % sprites.length]);

  const el = document.getElementById('border-top');
  el.innerHTML = '';
  for (const s of chosen) {
    const img = document.createElement('img');
    img.src = s.file;
    img.alt = s.label;
    el.appendChild(img);
  }
}

// ---------------------------------------------------------------------------
// Completion sound + tab-title flash — no external audio asset needed
// ---------------------------------------------------------------------------

let audioCtx = null;
function playDingSound() {
  try {
    audioCtx = audioCtx || new (window.AudioContext || window.webkitAudioContext)();
    const now = audioCtx.currentTime;
    [880, 1174.66].forEach((freq, i) => {
      const osc = audioCtx.createOscillator();
      const gain = audioCtx.createGain();
      osc.type = 'sine';
      osc.frequency.value = freq;
      gain.gain.setValueAtTime(0, now + i * 0.15);
      gain.gain.linearRampToValueAtTime(0.2, now + i * 0.15 + 0.02);
      gain.gain.exponentialRampToValueAtTime(0.001, now + i * 0.15 + 0.5);
      osc.connect(gain).connect(audioCtx.destination);
      osc.start(now + i * 0.15);
      osc.stop(now + i * 0.15 + 0.5);
    });
  } catch { /* audio not available; fail silently */ }
}

let titleFlashHandle = null;
const originalTitle = document.title;
function startTitleFlash() {
  stopTitleFlash();
  let on = false;
  titleFlashHandle = setInterval(() => {
    document.title = on ? originalTitle : '🍽️ Dish ready!';
    on = !on;
  }, 1000);
}
function stopTitleFlash() {
  if (titleFlashHandle) { clearInterval(titleFlashHandle); titleFlashHandle = null; }
  document.title = originalTitle;
}

// ---------------------------------------------------------------------------
// View management
// ---------------------------------------------------------------------------

function showView(name) {
  document.querySelectorAll('.view').forEach(v => v.classList.remove('active'));
  document.getElementById(`view-${name}`).classList.add('active');
  document.getElementById('nav-home').classList.toggle('active', name === 'home' || name === 'setup' || name === 'cooking' || name === 'complete');
  document.getElementById('nav-book').classList.toggle('active', name === 'book');
}

// ---------------------------------------------------------------------------
// Timer / cooking loop
// ---------------------------------------------------------------------------

let homeAnimator = null;
let cookAnimator = null;

function initHomeScene() {
  const scene = document.getElementById('kitchen-scene');
  const { chefAnchor } = composeKitchenScene(scene, 'idle');
  const chefImg = placeChef(scene, chefAnchor, 'chef-idle');
  homeAnimator = new Animator(chefImg, state.data.chef.sections);
  homeAnimator.play('idle');
}

function formatMs(ms) {
  const totalSec = Math.max(0, Math.ceil(ms / 1000));
  const m = Math.floor(totalSec / 60);
  const s = totalSec % 60;
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
}

const RING_CIRCUMFERENCE = 2 * Math.PI * 54;
function updateProgressRing(remainingFraction) {
  const bar = document.getElementById('progress-ring-bar');
  const arc = Math.max(0, Math.min(1, remainingFraction)) * RING_CIRCUMFERENCE;
  bar.style.strokeDasharray = `${arc} ${RING_CIRCUMFERENCE}`;
}

function setStage(text) {
  const stageLabel = document.getElementById('countdown-stage');
  stageLabel.style.opacity = '0';
  setTimeout(() => { stageLabel.textContent = text; stageLabel.style.opacity = '1'; }, 200);
}

// Builds the scene + chef animator for a cooking session. Shared by a fresh
// start and by restoring a session after a page reload.
function setupCookingScene() {
  const scene = document.getElementById('cooking-scene');
  const { chefAnchor } = composeKitchenScene(scene, 'cooking');
  const chefImg = placeChef(scene, chefAnchor, 'chef-sprite');
  cookAnimator = new Animator(chefImg, state.data.chef.sections);
}

// Walking, the ingredient-gathering vignette, and chopping are all either
// looping or a single non-repeating pass, so the stage sequence is driven on
// a fixed timeline rather than an animation "onComplete" (which never fires
// for a looping section, and the previous version relied on this for
// "walking" — the chef used to walk forever and never start cooking).
function runIntroSequence() {
  document.getElementById('countdown-stage').textContent = 'The chef arrives & gathers ingredients…';
  cookAnimator.play('walking');
  state.timer.introTimers = [
    setTimeout(() => {
      setStage('Checking the recipe book…');
      cookAnimator.play('interaction');
    }, 1500),
    setTimeout(() => {
      setStage('Chopping ingredients…');
      cookAnimator.play('chopping');
    }, 4300),
    setTimeout(() => {
      setStage('Cooking in progress…');
      cookAnimator.play('stirring');
      state.timer.introDone = true;
    }, 7300),
  ];
}

function clearIntroTimers() {
  state.timer.introTimers.forEach(clearTimeout);
  state.timer.introTimers = [];
}

function startTicking() {
  if (state.timer.tickHandle) clearInterval(state.timer.tickHandle);
  const tick = () => {
    const remainingMs = Math.max(0, state.timer.endAt - Date.now());
    document.getElementById('countdown-readout').textContent = formatMs(remainingMs);
    updateProgressRing(remainingMs / state.timer.totalMs);
    if (remainingMs <= 0) {
      clearInterval(state.timer.tickHandle);
      clearIntroTimers();
      cookAnimator.stop();
      clearSession();
      finishCooking();
    }
  };
  tick();
  // A short interval keeps the readout smooth; actual elapsed time always
  // comes from Date.now() so drift/background-tab throttling can't desync it.
  state.timer.tickHandle = setInterval(tick, 250);
}

function startCookingSession(minutes) {
  state.timer.totalMs = minutes * 60 * 1000;
  state.timer.endAt = Date.now() + state.timer.totalMs;
  state.timer.paused = false;
  state.timer.introDone = false;
  saveSession();

  setupCookingScene();
  runIntroSequence();
  startTicking();

  document.getElementById('pause-cook-btn').textContent = 'Pause';
  showView('cooking');
}

function restoreActiveSession(session) {
  state.timer.totalMs = session.totalMs;
  state.timer.endAt = session.endAt;
  state.timer.paused = false;
  state.timer.introDone = true; // skip the intro flourish on reload, go straight to steady state

  setupCookingScene();
  document.getElementById('countdown-stage').textContent = 'Cooking in progress…';
  cookAnimator.play('stirring');
  startTicking();

  document.getElementById('pause-cook-btn').textContent = 'Pause';
  showView('cooking');
}

function restorePausedSession(session) {
  state.timer.totalMs = session.totalMs;
  state.timer.remainingAtPauseMs = session.remainingAtPauseMs;
  state.timer.paused = true;
  state.timer.introDone = true;

  setupCookingScene();
  cookAnimator.play('stirring');
  cookAnimator.stop();
  document.getElementById('countdown-stage').textContent = 'Paused';
  document.getElementById('countdown-readout').textContent = formatMs(session.remainingAtPauseMs);
  updateProgressRing(session.remainingAtPauseMs / session.totalMs);

  document.getElementById('pause-cook-btn').textContent = 'Resume';
  showView('cooking');
}

function togglePauseCooking() {
  if (state.timer.paused) {
    state.timer.endAt = Date.now() + state.timer.remainingAtPauseMs;
    state.timer.paused = false;
    document.getElementById('pause-cook-btn').textContent = 'Pause';
    document.getElementById('countdown-stage').textContent = 'Cooking in progress…';
    cookAnimator.play('stirring');
    startTicking();
  } else {
    state.timer.remainingAtPauseMs = Math.max(0, state.timer.endAt - Date.now());
    state.timer.paused = true;
    state.timer.introDone = true;
    clearIntroTimers();
    if (state.timer.tickHandle) clearInterval(state.timer.tickHandle);
    cookAnimator.stop();
    document.getElementById('countdown-stage').textContent = 'Paused';
    document.getElementById('pause-cook-btn').textContent = 'Resume';
  }
  saveSession();
}

function cancelCooking() {
  if (state.timer.tickHandle) clearInterval(state.timer.tickHandle);
  clearIntroTimers();
  if (cookAnimator) cookAnimator.stop();
  state.timer.totalMs = 0;
  clearSession();
  showView('home');
}

function pickRecipeToReveal() {
  const all = state.data.recipes.sprites;
  const locked = all.filter(r => !state.unlocked.has(r.id));
  const pool = locked.length ? locked : all; // once everything is unlocked, keep surprising with a repeat
  const recipe = pool[Math.floor(Math.random() * pool.length)];
  const isNew = !state.unlocked.has(recipe.id);
  if (isNew) state.unlocked.add(recipe.id);
  saveUnlocked();
  return { recipe, isNew };
}

function finishCooking() {
  const { recipe, isNew } = pickRecipeToReveal();

  document.getElementById('dish-image').src = recipe.file;
  document.getElementById('dish-name').textContent = recipe.label;
  document.getElementById('unlock-banner').classList.toggle('hidden', !isNew);
  updateBookBadge();

  const presentImg = document.getElementById('chef-presenting');
  const presentAnimator = new Animator(presentImg, state.data.chef.sections);
  presentAnimator.play('presenting');

  playDingSound();
  if (document.hidden) startTitleFlash();

  showView('complete');
}

function updateBookBadge() {
  document.getElementById('book-count').textContent = state.unlocked.size;
}

function renderRecipeBook() {
  const grid = document.getElementById('recipe-grid');
  grid.innerHTML = '';
  const all = state.data.recipes.sprites;
  for (const r of all) {
    const unlocked = state.unlocked.has(r.id);
    const card = document.createElement('div');
    card.className = 'recipe-card' + (unlocked ? '' : ' locked');
    const img = document.createElement('img');
    img.src = r.file;
    img.alt = unlocked ? r.label : 'locked recipe';
    const name = document.createElement('div');
    name.className = 'rname';
    name.textContent = unlocked ? r.label : '???';
    card.appendChild(img);
    card.appendChild(name);
    grid.appendChild(card);
  }
  document.getElementById('collection-complete').classList.toggle('hidden', state.unlocked.size < all.length);
}

function resetProgress() {
  state.unlocked = new Set();
  saveUnlocked();
  updateBookBadge();
  renderRecipeBook();
}

// ---------------------------------------------------------------------------
// Duration dial wiring
// ---------------------------------------------------------------------------

let selectedMinutes = 25;
const DIAL_MAX_MINUTES = 180;

function setDialMinutes(minutes, { deselectPresets = false } = {}) {
  selectedMinutes = minutes;
  document.getElementById('dial-readout').textContent = `${String(minutes).padStart(2, '0')}:00`;
  const angle = Math.min(minutes, DIAL_MAX_MINUTES) / DIAL_MAX_MINUTES * 360;
  document.getElementById('dial-hand').style.transform = `translateX(-50%) rotate(${angle}deg)`;
  if (deselectPresets) {
    document.querySelectorAll('.duration-btn').forEach(b => b.classList.remove('selected'));
  }
}

function wireSetupView() {
  const buttons = document.querySelectorAll('.duration-btn');
  const customRange = document.getElementById('custom-range');
  buttons.forEach(btn => {
    btn.addEventListener('click', () => {
      buttons.forEach(b => b.classList.remove('selected'));
      btn.classList.add('selected');
      if (btn.dataset.min === 'custom') {
        customRange.classList.remove('hidden');
        setDialMinutes(Number(customRange.value));
      } else {
        customRange.classList.add('hidden');
        setDialMinutes(Number(btn.dataset.min));
      }
    });
  });
  customRange.addEventListener('input', () => setDialMinutes(Number(customRange.value)));

  // The dial itself is a real input too: drag the hand to set minutes directly.
  const dial = document.getElementById('dial');
  let dragging = false;

  const minutesFromEvent = evt => {
    const rect = dial.getBoundingClientRect();
    const cx = rect.left + rect.width / 2;
    const cy = rect.top + rect.height / 2;
    const dx = evt.clientX - cx;
    const dy = evt.clientY - cy;
    // The hand rests pointing straight down at 0deg (see .dial-hand's
    // transform-origin) and CSS rotate() is clockwise-positive, so 0deg maps
    // to "pointing down", not "pointing up".
    let angle = Math.atan2(-dx, dy) * 180 / Math.PI;
    if (angle < 0) angle += 360;
    return Math.max(1, Math.round(angle / 360 * DIAL_MAX_MINUTES));
  };

  dial.addEventListener('pointerdown', evt => {
    dragging = true;
    dial.setPointerCapture(evt.pointerId);
    customRange.classList.remove('hidden');
    const minutes = minutesFromEvent(evt);
    customRange.value = Math.min(minutes, Number(customRange.max));
    setDialMinutes(minutes, { deselectPresets: true });
  });
  dial.addEventListener('pointermove', evt => {
    if (!dragging) return;
    const minutes = minutesFromEvent(evt);
    customRange.value = Math.min(minutes, Number(customRange.max));
    setDialMinutes(minutes, { deselectPresets: true });
  });
  dial.addEventListener('pointerup', () => { dragging = false; });
  dial.addEventListener('pointercancel', () => { dragging = false; });
}

// ---------------------------------------------------------------------------
// Boot
// ---------------------------------------------------------------------------

async function main() {
  await loadData();
  initHomeScene();
  decorateBorders();
  wireSetupView();
  updateBookBadge();
  setDialMinutes(25);

  document.getElementById('start-cooking-btn').addEventListener('click', () => showView('setup'));
  document.getElementById('back-to-home').addEventListener('click', () => showView('home'));
  document.getElementById('begin-timer-btn').addEventListener('click', () => startCookingSession(selectedMinutes));
  document.getElementById('pause-cook-btn').addEventListener('click', togglePauseCooking);
  document.getElementById('cancel-cook-btn').addEventListener('click', cancelCooking);
  document.getElementById('done-btn').addEventListener('click', () => showView('home'));
  document.getElementById('nav-home').addEventListener('click', () => showView('home'));
  document.getElementById('nav-book').addEventListener('click', () => { renderRecipeBook(); showView('book'); });
  document.getElementById('reset-progress-btn').addEventListener('click', () => {
    if (confirm('Clear your entire recipe collection? This can\'t be undone.')) resetProgress();
  });

  document.addEventListener('visibilitychange', () => { if (!document.hidden) stopTitleFlash(); });

  // Resume an in-progress focus session if the page was reloaded mid-cook.
  const session = loadSession();
  if (session) {
    if (session.paused) {
      restorePausedSession(session);
    } else if (session.endAt > Date.now()) {
      restoreActiveSession(session);
    } else {
      // The timer ran out while the tab was closed/reloaded — still award the dish.
      state.timer.totalMs = session.totalMs;
      clearSession();
      finishCooking();
    }
  }
}

main();
