// ---------------------------------------------------------------------------
// Focus Kitchen — data-driven pixel kitchen timer
// All sprite geometry below is loaded from data/*.json, which was generated by
// measuring the source reference sheets (see data/*.json "source_bbox" / "note"
// fields for provenance). Nothing here hardcodes sprite pixel coordinates.
// ---------------------------------------------------------------------------

const STORAGE_KEY = 'focus-kitchen-unlocked-recipes';

const state = {
  data: { ingredients: null, tiles: null, chef: null, recipes: null },
  unlocked: loadUnlocked(),
  timer: { totalMs: 0, remainingMs: 0, tickHandle: null, stage: null },
  animators: [],
};

function loadUnlocked() {
  try {
    return new Set(JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'));
  } catch { return new Set(); }
}
function saveUnlocked() {
  localStorage.setItem(STORAGE_KEY, JSON.stringify([...state.unlocked]));
}

// ---------------------------------------------------------------------------
// Data loading
// ---------------------------------------------------------------------------

async function loadData() {
  const [ingredients, tiles, chef, recipes] = await Promise.all([
    fetch('data/ingredients.json').then(r => r.json()),
    fetch('data/tiles.json').then(r => r.json()),
    fetch('data/chef_animations.json').then(r => r.json()),
    fetch('data/recipes.json').then(r => r.json()),
  ]);
  state.data = { ingredients, tiles, chef, recipes };
}

function tileById(id) {
  return state.data.tiles.sprites.find(s => s.id === id);
}

// ---------------------------------------------------------------------------
// Animator: cycles an <img> through a named animation section's frames
// ---------------------------------------------------------------------------

class Animator {
  constructor(imgEl, sections) {
    this.img = imgEl;
    this.sections = sections;
    this.handle = null;
    this.frameIndex = 0;
    this.current = null;
    this.onComplete = null;
  }
  play(name, { onComplete } = {}) {
    this.stop();
    const section = this.sections[name];
    if (!section) return;
    this.current = name;
    this.frameIndex = 0;
    this.onComplete = onComplete || null;
    this._render(section);
    this.handle = setInterval(() => this._advance(section), section.frame_ms);
  }
  _advance(section) {
    this.frameIndex++;
    if (this.frameIndex >= section.frames.length) {
      if (section.loop) {
        this.frameIndex = 0;
      } else {
        this.frameIndex = section.frames.length - 1;
        this._render(section);
        this.stop();
        if (this.onComplete) this.onComplete();
        return;
      }
    }
    this._render(section);
  }
  _render(section) {
    this.img.src = section.frames[this.frameIndex].file;
  }
  stop() {
    if (this.handle) { clearInterval(this.handle); this.handle = null; }
  }
}

// ---------------------------------------------------------------------------
// Scene composition — layers floor / wall / counters / appliances / chef
// ---------------------------------------------------------------------------

function composeKitchenScene(container) {
  container.innerHTML = '';
  const t = id => tileById(id).file;

  container.style.backgroundImage = `url(${t('floor_tile_stone')})`;
  container.style.backgroundSize = '128px 128px';
  container.style.backgroundRepeat = 'repeat';
  container.style.backgroundPosition = 'top';

  const floor = document.createElement('div');
  floor.className = 'scene-layer';
  Object.assign(floor.style, {
    left: 0, right: 0, bottom: 0, height: '58%',
    backgroundImage: `url(${t('floor_tile_tan')})`,
    backgroundSize: '110px 122px', backgroundRepeat: 'repeat',
  });
  container.appendChild(floor);

  const layers = [
    { id: 'wood_floor_panel_a', style: { left: '4%', bottom: '4%', width: '150px', zIndex: 1 } },
    { id: 'cabinet_upper_run',  style: { left: '6%', top: '2%', width: '46%', zIndex: 2 } },
    { id: 'shelf_wood',         style: { right: '4%', top: '4%', width: '17%', zIndex: 2 } },
    { id: 'cabinet_lower_run',  style: { left: '4%', bottom: '20%', width: '58%', zIndex: 2 } },
    { id: 'fridge',             style: { right: '4%', bottom: '10%', width: '17%', zIndex: 2 } },
    { id: 'extractor_hood',     style: { left: '10%', top: '20%', width: '20%', zIndex: 3 } },
    { id: 'stove_range',        style: { left: '9%', bottom: '24%', width: '38%', zIndex: 3 } },
    { id: 'utensil_rack',       style: { left: '48%', top: '18%', width: '15%', zIndex: 3 } },
  ];
  for (const layer of layers) {
    const img = document.createElement('img');
    img.className = 'scene-layer';
    img.src = t(layer.id);
    Object.assign(img.style, { position: 'absolute', height: 'auto', ...layer.style, zIndex: String(layer.style.zIndex) });
    container.appendChild(img);
  }

  return { chefAnchor: { left: '16%', bottom: '22%', width: '110px', zIndex: 4 } };
}

function placeChef(container, anchor, imgId) {
  const img = document.createElement('img');
  img.id = imgId;
  img.className = 'chef-sprite scene-layer';
  Object.assign(img.style, { position: 'absolute', height: 'auto', ...anchor });
  container.appendChild(img);
  return img;
}

function decorateBorders() {
  const ingredientFiles = state.data.ingredients.sprites.map(s => s.file);
  const pick = n => {
    const out = [];
    for (let i = 0; i < n; i++) out.push(ingredientFiles[(i * 7) % ingredientFiles.length]);
    return out;
  };

  const topFiles = pick(10);
  const sideFiles = pick(8);

  paintBorder(document.getElementById('border-top'), topFiles, 'row');
  paintBorder(document.getElementById('border-left'), sideFiles, 'col');
  paintBorder(document.getElementById('border-right'), sideFiles.slice().reverse(), 'col');
}

function paintBorder(el, files, direction) {
  el.innerHTML = '';
  el.style.display = 'flex';
  el.style.flexDirection = direction === 'row' ? 'row' : 'column';
  el.style.justifyContent = 'space-around';
  el.style.alignItems = 'center';
  el.style.background = 'var(--bg-panel)';
  for (const f of files) {
    const img = document.createElement('img');
    img.src = f;
    img.style.width = '32px';
    img.style.height = '32px';
    img.style.objectFit = 'contain';
    el.appendChild(img);
  }
}

// ---------------------------------------------------------------------------
// View management
// ---------------------------------------------------------------------------

function showView(name) {
  document.querySelectorAll('.view').forEach(v => v.classList.remove('active'));
  document.getElementById(`view-${name}`).classList.add('active');
  document.getElementById('nav-home').classList.toggle('active', name === 'home' || name === 'setup' || name === 'cooking' || name === 'complete');
  document.getElementById('nav-book').classList.toggle('active', name === 'book');
}

// ---------------------------------------------------------------------------
// Timer / cooking loop
// ---------------------------------------------------------------------------

let homeAnimator = null;
let cookAnimator = null;

function initHomeScene() {
  const scene = document.getElementById('kitchen-scene');
  const anchor = composeKitchenScene(scene);
  const chefImg = placeChef(scene, anchor, 'chef-idle');
  homeAnimator = new Animator(chefImg, state.data.chef.sections);
  homeAnimator.play('idle');
}

function formatMs(ms) {
  const totalSec = Math.max(0, Math.ceil(ms / 1000));
  const m = Math.floor(totalSec / 60);
  const s = totalSec % 60;
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
}

function startCookingSession(minutes) {
  state.timer.totalMs = minutes * 60 * 1000;
  state.timer.remainingMs = state.timer.totalMs;

  const scene = document.getElementById('cooking-scene');
  scene.querySelectorAll('.scene-layer').forEach(el => el.remove());
  const t = id => tileById(id).file;
  scene.style.backgroundImage = `linear-gradient(180deg, rgba(74,55,40,0.0) 0%, rgba(58,42,29,0.0) 100%), url(${t('stove_range')})`;
  scene.style.backgroundSize = 'auto 60%';
  scene.style.backgroundRepeat = 'no-repeat';
  scene.style.backgroundPosition = 'center 90%';

  const chefImg = document.getElementById('chef-sprite');
  cookAnimator = new Animator(chefImg, state.data.chef.sections);

  const stageLabel = document.getElementById('countdown-stage');

  cookAnimator.play('walking', {
    onComplete: () => {
      stageLabel.textContent = 'Chopping ingredients…';
      cookAnimator.play('chopping');
      setTimeout(() => {
        stageLabel.textContent = 'Cooking in progress…';
        cookAnimator.play('stirring');
      }, 3000);
    },
  });
  stageLabel.textContent = 'The chef arrives & gathers ingredients…';

  document.getElementById('countdown-readout').textContent = formatMs(state.timer.remainingMs);

  const tickMs = 250;
  state.timer.tickHandle = setInterval(() => {
    state.timer.remainingMs -= tickMs;
    document.getElementById('countdown-readout').textContent = formatMs(state.timer.remainingMs);
    if (state.timer.remainingMs <= 0) {
      clearInterval(state.timer.tickHandle);
      cookAnimator.stop();
      finishCooking();
    }
  }, tickMs);

  showView('cooking');
}

function cancelCooking() {
  if (state.timer.tickHandle) clearInterval(state.timer.tickHandle);
  if (cookAnimator) cookAnimator.stop();
  showView('home');
}

function pickRecipeToReveal() {
  const all = state.data.recipes.sprites;
  const locked = all.filter(r => !state.unlocked.has(r.id));
  const pool = locked.length ? locked : all; // once everything is unlocked, keep surprising with a repeat
  const recipe = pool[Math.floor(Math.random() * pool.length)];
  const isNew = !state.unlocked.has(recipe.id);
  if (isNew) state.unlocked.add(recipe.id);
  saveUnlocked();
  return { recipe, isNew };
}

function finishCooking() {
  const { recipe, isNew } = pickRecipeToReveal();

  document.getElementById('dish-image').src = recipe.file;
  document.getElementById('dish-name').textContent = recipe.label;
  document.getElementById('unlock-banner').classList.toggle('hidden', !isNew);
  updateBookBadge();

  const presentImg = document.getElementById('chef-presenting');
  const presentAnimator = new Animator(presentImg, state.data.chef.sections);
  presentAnimator.play('presenting');

  showView('complete');
}

function updateBookBadge() {
  document.getElementById('book-count').textContent = state.unlocked.size;
}

function renderRecipeBook() {
  const grid = document.getElementById('recipe-grid');
  grid.innerHTML = '';
  for (const r of state.data.recipes.sprites) {
    const unlocked = state.unlocked.has(r.id);
    const card = document.createElement('div');
    card.className = 'recipe-card' + (unlocked ? '' : ' locked');
    const img = document.createElement('img');
    img.src = r.file;
    img.alt = unlocked ? r.label : 'locked recipe';
    const name = document.createElement('div');
    name.className = 'rname';
    name.textContent = unlocked ? r.label : '???';
    card.appendChild(img);
    card.appendChild(name);
    grid.appendChild(card);
  }
}

// ---------------------------------------------------------------------------
// Duration dial wiring
// ---------------------------------------------------------------------------

let selectedMinutes = 25;

function setDialMinutes(minutes) {
  selectedMinutes = minutes;
  document.getElementById('dial-readout').textContent = `${String(minutes).padStart(2, '0')}:00`;
  const angle = Math.min(minutes, 120) / 120 * 360;
  document.getElementById('dial-hand').style.transform = `translateX(-50%) rotate(${angle}deg)`;
}

function wireSetupView() {
  const buttons = document.querySelectorAll('.duration-btn');
  const customRange = document.getElementById('custom-range');
  buttons.forEach(btn => {
    btn.addEventListener('click', () => {
      buttons.forEach(b => b.classList.remove('selected'));
      btn.classList.add('selected');
      if (btn.dataset.min === 'custom') {
        customRange.classList.remove('hidden');
        setDialMinutes(Number(customRange.value));
      } else {
        customRange.classList.add('hidden');
        setDialMinutes(Number(btn.dataset.min));
      }
    });
  });
  customRange.addEventListener('input', () => setDialMinutes(Number(customRange.value)));
}

// ---------------------------------------------------------------------------
// Boot
// ---------------------------------------------------------------------------

async function main() {
  await loadData();
  initHomeScene();
  decorateBorders();
  wireSetupView();
  updateBookBadge();
  setDialMinutes(25);

  document.getElementById('start-cooking-btn').addEventListener('click', () => showView('setup'));
  document.getElementById('back-to-home').addEventListener('click', () => showView('home'));
  document.getElementById('begin-timer-btn').addEventListener('click', () => startCookingSession(selectedMinutes));
  document.getElementById('cancel-cook-btn').addEventListener('click', cancelCooking);
  document.getElementById('done-btn').addEventListener('click', () => showView('home'));
  document.getElementById('nav-home').addEventListener('click', () => showView('home'));
  document.getElementById('nav-book').addEventListener('click', () => { renderRecipeBook(); showView('book'); });
}

main();
